In [129]:
import pandas as pd
import jieba

In [130]:
from google.colab import drive

drive.mount('/content/drive')  ## https://blog.csdn.net/sdaujz/article/details/106531632
                 ## https://blog.csdn.net/sdaujz/article/details/106531632


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [131]:
cd /content/drive//My Drive/CODE/python/7600

/content/drive/My Drive/CODE/python/7600


In [132]:
data = pd.read_csv("2021-07-27_articles.csv")
data

Unnamed: 0  ...                                            Article
0             0  ...  ['\u3000\u3000炒股就看金麒麟分析师研报，权威，专业，及时，全面，助您挖掘潜力主...
1             1  ...  ['\u3000\u3000炒股就看金麒麟分析师研报，权威，专业，及时，全面，助您挖掘潜力主...
2             2  ...  ['\u3000\u3000炒股就看金麒麟分析师研报，权威，专业，及时，全面，助您挖掘潜力主...
3             3  ...  ['投资研报', '军工板块15天涨15%，五张图看懂基金重仓军工股的调仓变化，公募最看好这...
4             4  ...  ['\u3000\u3000炒股就看金麒麟分析师研报，权威，专业，及时，全面，助您挖掘潜力主...
..          ...  ...                                                ...
216         216  ...  ['\u3000\u30007月22日，科创板开市两周年之际，由《财经》杂志与科创数据研究中...
217         217  ...  ['\u3000\u3000发展绿色金融，是实现绿色发展的重要措施，也是我国供给侧结构性改革...
218         218  ...  ['\u3000\u3000随着中国经济的稳健发展，居民收入持续增长，全社会财富管理需求日益...
219         219  ...  ['近日，新东方在线（01797.HK）与天津大学教育学院联合举办开放日活动，邀请教育学院的...
220         220  ...  ['\u3000\u30007月19日，第五届中国家居品牌大会在广州正式落下帷幕，会上发布了...

[221 rows x 4 columns]

In [133]:
urls = pd.read_csv("2021-07-27_stock_link.csv",header=0)
urls 
# 【todo】data和urls的行数不一样，需要存data时直接加一列url

https://finance.sina.com.cn/zt_d/hnddby/
0               https://finance.sina.com.cn/zt_d/xdfgg
1       https://finance.sina.com.cn/zt_d/2021_qdzgcflt
2            http://finance.sina.com.cn/video/?from=g1
3                    http://finance.sina.com.cn/stock/
4    https://finance.sina.com.cn/mobile/comfinancew...
..                                                 ...
723  https://finance.sina.com.cn/mobile/comfinancew...
724  http://vip.stock.finance.sina.com.cn/q/go.php/...
725  http://finance.sina.com.cn/stock/message/upchi...
726  http://vip.stock.finance.sina.com.cn/q/go.php/...
727  http://vip.stock.finance.sina.com.cn/q/go.php/...

[728 rows x 1 columns]

In [134]:
data['Article'][0]

"['\\u3000\\u3000炒股就看金麒麟分析师研报，权威，专业，及时，全面，助您挖掘潜力主题机会！', '\\u3000\\u3000原标题：29天涨幅达36%，顶级游资纷纷抢筹，有色金属后市如何走？', '\\u3000\\u3000财联社7月27日讯，受益于新能源等下游领域需求上行，有色金属板块早盘全线走强，', '\\u3000\\u3000宏达股份涨停，鑫铂股份、联瑞新材、铜陵有色涨超9%，电工合金、洛阳钼业、西部矿业等多股大幅拉升。', '\\u3000\\u3000截至发文，近29个交易日有色金属板块涨幅高达36%，在众多板块中名列前茅。另外，板块中也诞生了众多大牛股。', '\\u3000\\u3000西部矿业近日公布的半年报显示，上半年实现归属于上市公司股东的净利润14.11亿元，同比增336.41%。同时二季度获得高毅资本加仓。', '\\u3000\\u3000盛屯矿业此前发布半年度业绩预告称2021年半年度实现归属于上市公司股东的净利润与上年同期相比增加6.67亿元到7.57亿元，同比增加1803%到2046%。', '\\u3000\\u3000其中鹏欣资源连获顶级游资抢筹。资金面来看，昨日机构席位合计买入鹏欣资源2481.35万；华泰证券宁波柳汀街买入731.86万；', '\\u3000\\u3000三日龙虎榜上，另有顶级游资方新侠常用席位兴业证券陕西分公司占据二席，净买入1046.56万。', '\\u3000\\u3000从上周价格走势来看，有色金属涨跌互现，其中铜、铅价上涨，铝、锌价格下跌；橡胶价格走平。', '\\u3000\\u3000外资避险+极端天气+下游需求,助推有色金属价格上行', '\\u3000\\u3000此前有色金属板块历经近三个月调整，主要原因是市场对美联储紧缩性货币政策的预期和国内政府对商品保价稳供的决心。', '\\u3000\\u3000全球新冠疫情反复，美国长期国债收益率异常波动。安信证券表示，上周美国宣布失业金申请人数大福增加，避险情绪拉升贵金属价格。', '\\u3000\\u3000国内郑州、新乡等地区遭遇极端天气，下游铜、铝加工企业停工，供给端受到抑制有望助推基本金属价格上涨。中长期来看全球经济复苏的逻辑依然强劲，我们认为工业金属需求上行的动力依然维持。此外，新能源汽车需求旺季临近，西部

In [135]:
# jieba分词的demo【可跳过直接下一步】
import jieba
# 载入自定义词库（比如：所有股票名称/代码
# jieba.load_userdict("./dict/jieba_dict.txt")

jieba.enable_paddle()# 启动paddle模式。 0.40版之后开始支持，早期版本不支持

seg_list = jieba.cut("我来到北京清华大学",use_paddle=True) # 使用paddle模式
print("Paddle Mode: " + '/'.join(list(seg_list)))

seg_list = jieba.cut("我来到北京清华大学", cut_all=True)
print("Full Mode: " + "/ ".join(seg_list))  # 全模式

seg_list = jieba.cut("我来到北京清华大学", cut_all=False)
print("Default Mode: " + "/ ".join(seg_list))  # 精确模式

seg_list = jieba.cut("他来到了网易杭研大厦")  # 默认是精确模式
print(", ".join(seg_list))

seg_list = jieba.cut_for_search("小明硕士毕业于中国科学院计算所，后在日本京都大学深造")  # 搜索引擎模式
print(", ".join(seg_list))

Paddle enabled successfully......


Paddle Mode: 我/来到/北京清华大学
Full Mode: 我/ 来到/ 北京/ 清华/ 清华大学/ 华大/ 大学
Default Mode: 我/ 来到/ 北京/ 清华大学
他, 来到, 了, 网易, 杭研, 大厦
小明, 硕士, 毕业, 于, 中国, 科学, 学院, 科学院, 中国科学院, 计算, 计算所, ，, 后, 在, 日本, 京都, 大学, 日本京都大学, 深造


In [136]:
def getJiebaList(x):
  # 对字符串'['string1','string1']'结巴分词¶，得到list：[[string1 word],[string2 word]]
  result = []
  y = x.strip("[").strip("]").split(", ")
  for string in y:
    tmp = " ".join(jieba.cut(string.strip("\'").strip('\\u3000\\u3000').strip('\u3000\u3000'))).split()
    result.append(tmp)
  return result

def transListsToList(x):
  # 将包含多个lists的list x合并为1个list(即一篇文章的词汇存在1个list中)
  return [i for p in x for i in p]

data['doc_Jieba_List']=data.Article.apply(getJiebaList)
data['doc_Jieba']=data.doc_Jieba_List.apply(transListsToList)
data

Unnamed: 0  ...                                          doc_Jieba
0             0  ...  [炒股, 就, 看, 金麒麟, 分析师, 研报, ，, 权威, ，, 专业, ，, 及时, ...
1             1  ...  [炒股, 就, 看, 金麒麟, 分析师, 研报, ，, 权威, ，, 专业, ，, 及时, ...
2             2  ...  [炒股, 就, 看, 金麒麟, 分析师, 研报, ，, 权威, ，, 专业, ，, 及时, ...
3             3  ...  [投资, 研报, 军工, 板块, 15, 天涨, 15%, ，, 五张, 图看, 懂, 基金...
4             4  ...  [炒股, 就, 看, 金麒麟, 分析师, 研报, ，, 权威, ，, 专业, ，, 及时, ...
..          ...  ...                                                ...
216         216  ...  [7, 月, 22, 日, ，, 科创板, 开市, 两周年, 之际, ，, 由, 《, 财经...
217         217  ...  [发展, 绿色, 金融, ，, 是, 实现, 绿色, 发展, 的, 重要, 措施, ，, 也...
218         218  ...  [随着, 中国, 经济, 的, 稳健, 发展, ，, 居民收入, 持续增长, ，, 全, 社...
219         219  ...  [近日, ，, 新东方, 在线, （, 01797, ., HK, ）, 与, 天津大学, ...
220         220  ...  [7, 月, 19, 日, ，, 第五届, 中国, 家居, 品牌, 大会, 在, 广州, 正...

[221 rows x 6 columns]

In [137]:
# Selecting frequently-used words：选择出现次数大于kappa的词汇（kappa为超参数），对应论文中D__freq
## 计算包含词汇i的文章数，存在字典dict_word_ariticles中；然后计算每篇文章的词汇set set_word_ariticles，
## 【todo】需要对应到url核对下数据是否准确
dict_word_ariticles = {}
for article_list in data['doc_Jieba']:
  set_word_ariticles = set(article_list)
  for word in list(set_word_ariticles):
    if word in dict_word_ariticles:
      dict_word_ariticles[word] += 1
    else:
      dict_word_ariticles[word] = 1
# dict_word_ariticles


## 选择出现次数大于kappa的词汇（kappa为超参数）
kappa = 20
frequent_dict = [k for k, v in dict_word_ariticles.items() if v > kappa]

# 词到ID的映射, 使得每个词有一个ID
D__freq = dict(zip(frequent_dict, range(len(frequent_dict))))
# sorted(D__freq)

### Factor modeling【todo】
$ X = FB^T + U$

### Learning factors and idiosyncratic components【todo】
（0）求X：

（1.1）指定k，求F：$F=sqrt(n)*(XX^T的最大的前k个特征值）$

（1.2）求出k，再求F

（2） 根据X和F，求B：$B=X^TF/n$

（3）根据X，F和B，求U：$U=X-FB^T$

In [138]:
# sorted(D__freq.items(), key=lambda item:item[1])

In [139]:
# （0）求X
from collections import Counter
from itertools import chain
import numpy as np
documents = data['doc_Jieba']
def word_matrix(docs, dictionary, word_num, doc_num ):
    '''计算词频矩阵：行表示词语，列表示文档'''
    # 词到ID的映射, 使得每个词有一个ID
    # dictionary = dict(zip(words, range(len(words))))
    #print(dictionary)
    # 创建一个空的矩阵, 行数等于文档数, 列数等于词数
    matrix = np.zeros((doc_num,  word_num))
    # 逐个文档统计词频
    for row in range(doc_num):  # row 表示矩阵第几行，即第几个文档
        # 统计词频
        count = Counter(docs[row])#其实是个词典，词典元素为：{单词：次数}。
        for word in count:
          if word in D__freq:
            # 用word的id表示word在矩阵中的行数，该文档表示列数。
            col= dictionary[word] # col表示矩阵第几列，即第几个单词
            # 把词频赋值给矩阵
            matrix[row,col] = count[word]
    return matrix
 
X = word_matrix(documents, D__freq, len(D__freq), len(documents))
print("Word frequency matrix is:",X) ##【todo】根据url对应的文章，检查看词频是否正确

Word frequency matrix is: [[2. 1. 1. ... 0. 0. 0.]
 [4. 2. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 ...
 [3. 0. 1. ... 0. 0. 0.]
 [2. 1. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]]


In [140]:
# （1.1）指定k，求F：$F=sqrt(n)*(XX^T的最大的前k个特征值）$。【todo】检查下算得对不对 ；【todo】这里k是超参数
# 【参考：https://blog.csdn.net/w450468524/article/details/54885773
import numpy as np
n = len(documents)
k = 10

eigenvalue, featurevector = np.linalg.eig(np.matmul(X,X.T))
sorted_indices = np.argsort(eigenvalue)
# 上面得到的sorted_indices就是特征值排序后的结果，巧妙的是这里是用数组下标来表示的，也就是说其中存放的是特征值由小到大的顺序排序时对应的下标[0, 4, 1, 3, 2]，而不是直接存放特征值。
# 下一步就是取前k大的特征向量了：
topk_evecs = featurevector[:,sorted_indices[:-k-1:-1]]

F = np.sqrt(n) * topk_evecs
print("F = ",F)

# 复数：
# 实数部分和虚数部分都是浮点数
# 虚数部分必须有j或J
# 下面是些得数：
# 64.23+1j            4.34-8.5j            0.23-8.33j            1.23e-0.45+6.5e+0.83j              -1.23-3.5j            -0.34-0j
# 复数中的内建属性

# （1.2）求出k，再求F：

# （2） 根据X和F，求B：$B=X^TF/n$
B = np.matmul(X.T,F) / n
print("B =",B)
# （3）根据X，F和B，求U：$U=X-FB^T$
U = X - np.matmul(F,B.T)
print("U =",U)

F =  [[ 0.55053597+0.j  0.01279708+0.j  0.81303175+0.j ...  0.0258188 +0.j
  -0.70000767+0.j  0.19366907+0.j]
 [ 1.22790048+0.j  0.67819775+0.j -0.41109158+0.j ...  0.58464359+0.j
  -0.67910261+0.j  2.16014315+0.j]
 [ 0.55136902+0.j  0.20966917+0.j  0.33916881+0.j ...  0.68088325+0.j
  -0.5788779 +0.j -0.13633894+0.j]
 ...
 [ 1.14193694+0.j  0.9447208 +0.j  0.03724166+0.j ... -1.16005805+0.j
   0.04776228+0.j -1.25646298+0.j]
 [ 0.31998361+0.j  0.25312309+0.j  0.07968354+0.j ... -0.65986242+0.j
   0.58423554+0.j -0.06571552+0.j]
 [ 0.30971732+0.j  0.06683968+0.j  0.25618672+0.j ... -0.30366847+0.j
   0.07305033+0.j -0.22649428+0.j]]
B = [[ 3.76695527e+00+0.j -5.07419278e-01+0.j -6.32304550e-01+0.j ...
  -1.29829112e-01+0.j  5.65153484e-02+0.j  8.20260195e-01+0.j]
 [ 1.94923486e-01+0.j  3.05238130e-02+0.j  7.25606919e-02+0.j ...
   1.60506270e-03+0.j  4.85369005e-02+0.j  1.07530334e-01+0.j]
 [ 1.27736924e+00+0.j -1.50973105e-03+0.j -3.04423085e-02+0.j ...
  -4.24572516e-02+0.j -2.111754

### Learning conditional sentiment-charged words S【todo】

In [141]:
# 1.根据Y和F做线性回归，求残差Y_u
# 真实的Y未知，先随机生成浮点数【todo】计算出真实的Y
from numpy import random
Y = random.rand(F.shape[0])
# 判断F的每个复数元素是否为实数：
np.all(np.imag(F)==0) #np.imag(F)：提取复数的虚部；np.real(F)：提取复数的实部 
                      #np.any()，np.all()，来判断一个矩阵中是否有0元素或一个矩阵是否是零矩阵
F = np.real(F)
# 1.1.根据Y和F做线性回归，求Y_f_pred
#【参考：https://www.cnblogs.com/learnbydoing/p/12190168.html
from sklearn.linear_model import LinearRegression
model_Y_f = LinearRegression()
model_Y_f = model_Y_f.fit(F, Y) #np.real(F)：提取复数的实部
'''
# get result: y = b0 + b1x
r_sq = model_Y_f.score(F, Y)
print('coefficient of determination(𝑅²) :', r_sq)
# coefficient of determination(𝑅²) : 0.715875613747954
print('intercept:', model_Y_f.intercept_)
# （标量） 系数b0 intercept: 5.633333333333329 -------this will be an array when y is also 2-dimensional
print('slope:', model_Y_f.coef_)
# （数组）斜率b1 slope: [0.54]        ---------this will be 2-d array when y is also 2-dimensional
'''
# predict response: given x, get y from the model y = b0+b1x
Y_f_pred = model_Y_f.predict(F)
# 1.2.求残差Y_u
Y_u = Y - Y_f_pred
Y_u.shape

(221,)

In [146]:
# 2.求Y_u与U的相关系数，然后按照论文，根据$S = {j:|corr(U_j,Y_u)|>alpha & {j:k_j>=kappa}$ ，这里alpha和kappa是超参数
#   需要注意的是：因为U_j来自于D_freq，所以已经满足{j:k_j>=kappa}了。 
#   另外，接下来我们会直接取相关度绝对值排前alpha的U_j，所以下面出现的alpha和上述提到论文里含义稍有区别，不过作用是一样的。

# 【希腊字母与英文对照：https://blog.csdn.net/bxlover007/article/details/105725593
#【求相关系数：https://www.cnblogs.com/marszhw/p/12175454.html
import random
import numpy as np
# 判断U的每个复数元素是否为实数：
np.all(np.imag(U)==0) #np.imag(U)：提取复数的虚部；np.real(U)：提取复数的实部 
                      #np.any()，np.all()，来判断一个矩阵中是否有0元素或一个矩阵是否是零矩阵
U = np.real(U)
corr_U_j__Y_u = np.zeros(len(D__freq))
for j in range(len(D__freq)):
  tmp = np.array([Y_u, U[:,j]])
  corr_U_j__Y_u[j] = np.corrcoef(tmp)[0][1] # np.cov(tmp) # 计算协方差矩阵 ; np.corrcoef(tmp) # 计算相关系数矩阵
corr_abs_U_j__Y_u = abs(corr_U_j__Y_u)
# 下一步就是取前alpha大的相关度绝对值对应的U_j的下标：
sorted_indices_U = np.argsort(corr_abs_U_j__Y_u)
sorted_indices_U #上面得到的sorted_indices_U就是相关度绝对值排序后的结果，巧妙的是这里是用数组下标来表示的，也就是说其中存放的是相关度绝对值由小到大的顺序排序时对应的下标[0, 4, 1, 3, 2]，而不是直接存放相关度绝对值。
# print("Is min equals:",min(corr_abs_U_j__Y_u)==corr_abs_U_j__Y_u[sorted_indices_U[0]]) # 验证排序正确
alpha = 1000
topk_U_j = sorted_indices_U[:-alpha-1:-1]
# 最后得到情感词汇集S
S = [k for k,v in D__freq.items() if v in topk_U_j]

In [154]:
len(S)

905

In [155]:
len(D__freq)

905